routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('/home', function () {
    return view('home');
});
    Route::resource('employee', EmployeesController::class);
    Route::GET('employee/vacation/{id}', 'EmployeesController@vacation')->name('employee.vacation');
    Route::GET('employee/certification/{id}', 'EmployeesController@certification')->name('employee.certification');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $fillable = ['registration_number','fullname','depart','hire_date','city','phone','address'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Employee;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();

        return \view('employees.index')->with([
            'employees' => $employees
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

       $this->validate($request,[
            'fullname' => 'required',
            'registration_number' => 'required|numeric|unique:employees,registration_number',
            'depart' => 'required',
            'hire_date' => 'required',
            'phone' => 'required|numeric',
            'address' => 'required',
            'city' => 'required',
        ]);
        Employee::create($request->except('_token'));
        return \redirect()->route('employee.index')->with([
            'success' => 'Employee added successfully'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::where('registration_number',$id)->first();

        return \view('employees.show')->with([
            'employee' => $employee
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::where('registration_number',$id)->first();

        return \view('employees.edit')->with([
            'employee' => $employee
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $employee = Employee::where('registration_number',$id)->first();
               $this->validate($request,[
            'fullname' => 'required',
            'registration_number' => 'required|numeric|unique:employees,id,'.$employee->registration_number,
            'depart' => 'required',
            'hire_date' => 'required',
            'phone' => 'required|numeric',
            'address' => 'required',
            'city' => 'required',
        ]);
        $employee->update($request->except('_token','_method'));
        return \redirect()->route('employee.index')->with([
            'success' => 'Employee Updated successfully'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

         $employee = Employee::where('registration_number',$id)->first();
        $employee->delete();
         return \redirect()->route('employee.index')->with([
            'success' => 'Employee Deleted successfully'
        ]);
    }

        public function vacation($id)
    {

         $employee = Employee::where('registration_number',$id)->first();
          return \view('employees.vacation')->with([
            'employee' => $employee
        ]);
    }

          public function certification($id)
    {

         $employee = Employee::where('registration_number',$id)->first();
         return \view('employees.certification')->with([
            'employee' => $employee
        ]);
    }

}

resources/views/employees/certification.blade.php
@extends('adminlte::page')
@section('plugins.Datatables',true)
@section('title')
Employee Certification | laravel employee App
@endsection

@section('content_header')
<h1><i class="fa fa-user"></i> Employee Certification </h1>
@endsection

@section('content')
<div class="container">
     <div class="row my-5">
          <div class="col-lg-8 col-10 mx-auto">
            <p class="lead">
                <b>{{ $employee->fullname }}</b> is presently employed with me in the following :
            </p>
            <p class="lead">
                <b>{{ $employee->depart }}</b> department
            </p>
            <p class="lead">
                he is requesting a vacation starting from <b>_________</b>
            </p>
            <p class="lead">
                and ends on <b>_________</b>
            </p>
            <p class="m-5">
                ________
            </p>

          </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready(function(){
        $('#myTable').DataTable({
            dom : 'Bfrtip',
            buttons : [
                'copy',
                'excel',
                'pdf',
                'csv',
                'print',
                'colvis',
                'pageLength',
            ]
        });
    });
    function deleteEmp(id){
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {

                if (result.isConfirmed) {
                    document.getElementById(id).submit();
                    Swal.fire(
                    'Deleted!',
                    'Employee has been deleted.',
                    'success'
                )
            }
        })
    }

</script>
@if (session()->has('success'))
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '{{session()->get("success")}}',
            showConfirmButton: false,
            timer: 1500
        })
    </script>
@endif

@endsection

resources/views/employees/create.blade.php
@extends('adminlte::page')
@section('plugins.Datatables',true)
@section('title')
Add New Employees | laravel employee App
@endsection

@section('content_header')
<h1><i class="fa fa-user-plus text-red"></i> Add New Employees</h1>
@endsection

@section('content')
{{-- @include('layouts.alert') --}}
<div class="container">

     <div class="row">
          <div class="col-lg-8 mx-auto">
              <div class="card my-3">
                  <div class="card-header bg-info">
                      <div class="text-center text-uppercase ">
                         <h3>Add New Employees  <i class="fa fa-user-plus"></i></h3>
                      </div>
                  </div>
                  <div class="card-body">
                    <form action="{{ route('employee.store') }}" class="mt-5" method="POST">
                        @csrf
                        <div class="form-group">
                            <label class="text-info" for="fullname">Full Name: @error('fullname')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="fullname" placeholder="Full Name" class="form-control @error('fullname') is-invalid @enderror" value="{{ old('fullname') }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="registration_number">Registration Number: @error('registration_number')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="registration_number" placeholder="Registration Number" class="form-control @error('registration_number') is-invalid @enderror" value="{{ old('registration_number') }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="depart">Departement: @error('depart')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="depart" placeholder="Departement" class="form-control @error('depart') is-invalid @enderror" value="{{ old('depart') }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="hire_date">Hire date: @error('hire_date')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="date" name="hire_date" placeholder="Hire date" class="form-control @error('hire_date') is-invalid @enderror" value="{{ old('hire_date') }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="phone">Phone: @error('phone')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="tel" name="phone" placeholder="Phone" class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone') }}">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="address">Address: @error('address')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="address" placeholder="Address" class="form-control @error('address') is-invalid @enderror" value="{{ old('address') }}">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="city">City: @error('city')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="city" placeholder="City" class="form-control @error('city') is-invalid @enderror" value="{{ old('city') }}">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary form-control" type="submit">Add  <i class="fa fa-plus-circle"></i></button>
                        </div>
                    </form>

                  </div>
              </div>

          </div>
</div>
@endsection

@section('js')

@endsection

resources/views/employees/edit.blade.php
@extends('adminlte::page')
@section('plugins.Datatables',true)
@section('title')
Edit Employees | laravel employee App
@endsection

@section('content_header')
<h1><i class="fa fa-user-edit text-red"></i> Edit Employees</h1>
@endsection

@section('content')
{{-- @include('layouts.alert') --}}
<div class="container">

     <div class="row">
          <div class="col-lg-8 mx-auto">
              <div class="card my-3">
                  <div class="card-header bg-info">
                      <div class="text-center text-uppercase ">
                         <h3>Edit Employees  <i class="fa fa-user-edit"></i></h3>
                      </div>
                  </div>
                  <div class="card-body">
                    <form action="{{ route('employee.update',$employee->registration_number) }}" class="mt-5" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label class="text-info" for="fullname">Full Name: @error('fullname')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="fullname" placeholder="Full Name" class="form-control @error('fullname') is-invalid @enderror" value="{{ old('fullname',$employee->fullname) }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="registration_number">Registration Number: @error('registration_number')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="registration_number" placeholder="Registration Number" class="form-control @error('registration_number') is-invalid @enderror" value="{{ old('registration_number',$employee->registration_number) }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="depart">Departement: @error('depart')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="depart" placeholder="Departement" class="form-control @error('depart') is-invalid @enderror" value="{{ old('depart',$employee->depart) }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="hire_date">Hire date: @error('hire_date')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="date" name="hire_date" placeholder="Hire date" class="form-control @error('hire_date') is-invalid @enderror" value="{{ old('hire_date',$employee->hire_date) }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="phone">Phone: @error('phone')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="tel" name="phone" placeholder="Phone" class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone',$employee->phone) }}">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="address">Address: @error('address')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="address" placeholder="Address" class="form-control @error('address') is-invalid @enderror" value="{{ old('address',$employee->address) }}">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="city">City: @error('city')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="city" placeholder="City" class="form-control @error('city') is-invalid @enderror" value="{{ old('city',$employee->city) }}">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary form-control" type="submit">Update Employee  <i class="fa fa-user-edit" ></i></button>
                        </div>
                    </form>

                  </div>
              </div>

          </div>
</div>
@endsection

@section('js')

@endsection

resources/views/employees/index.blade.php
@extends('adminlte::page')
@section('plugins.Datatables',true)
@section('title')
List of Employees | laravel employee App
@endsection

@section('content_header')
<h1><i class="fa fa-list"></i> List of Employees</h1>
@endsection

@section('content')

     <div class="row">
          <div class="col-lg-10 col-10 mx-auto">
              <div class="card my-3">
                  <div class="card-header bg-info">
                      <div class="text-center text-uppercase ">
                         <h3>List of Employees</h3>
                      </div>
                  </div>
                  <div class="card-body">
                      <table id="myTable" class="table table-bordered table-striped">
                          <thead>
                              <tr>
                                  <th>id</th>
                                  <th>full-Name</th>
                                  <th>Department</th>
                                  <th>Hired-Date</th>
                                  <th></th>
                              </tr>
                            </thead>
                            <tbody class='text-center'>
                                 @foreach ($employees as $key => $employee)
                                 <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $employee->fullname }}</td>
                                    <td>{{ $employee->depart }}</td>
                                    <td>{{ $employee->hire_date }}</td>
                                    <td class="text-center">

                                        <button onclick="deleteEmp({{$employee->registration_number}})" type='submit' class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                        <a href="{{ route('employee.show',$employee->registration_number) }}" class="btn btn-primary"><i class="fa fa-eye"></i></a>
                                        <a href="{{ route('employee.edit',$employee->registration_number) }}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                        <form method='POST' id='{{$employee->registration_number}}' action="{{ route('employee.destroy',$employee->registration_number) }}">
                                            @csrf
                                            @method('delete')
                                        </form>
                                    </td>
                                </tr>
                                 @endforeach
                            </tbody>

                      </table>
                  </div>
              </div>

          </div>

@endsection

@section('js')
<script>
    $(document).ready(function(){
        $('#myTable').DataTable({
            dom : 'Bfrtip',
            buttons : [
                'copy',
                'excel',
                'pdf',
                'csv',
                'print',
                'colvis',
                'pageLength',
            ]
        });
    });
    function deleteEmp(id){
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {

                if (result.isConfirmed) {
                    document.getElementById(id).submit();
                    Swal.fire(
                    'Deleted!',
                    'Employee has been deleted.',
                    'success'
                )
            }
        })
    }

</script>
@if (session()->has('success'))
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '{{session()->get("success")}}',
            showConfirmButton: false,
            timer: 1500
        })
    </script>
@endif

@endsection

resources/views/employees/show.blade.php
@extends('adminlte::page')
@section('plugins.Datatables',true)
@section('title')
Employee Details | laravel employee App
@endsection

@section('content_header')
<h1><i class="fa fa-user text-red"></i> Employee Details</h1>
@endsection

@section('content')
{{-- @include('layouts.alert') --}}
<div class="container">

     <div class="row">
          <div class="col-lg-8 mx-auto">
              <div class="card my-3">
                  <div class="card-header bg-info">
                      <div class="text-center text-uppercase ">
                         <h3 class="text-dark">{{ $employee->fullname }} <i class="fa fa-user"> </i></h3>
                      </div>
                  </div>
                  <div class="my-2 text-center text-uppercase border-dark">
                    <a href="{{ route('employee.vacation',$employee->registration_number) }}" class="btn btn-outline-primary">
                        Vacation Request
                    </a>
                     <a href="{{ route('employee.certification',$employee->registration_number) }}" class="btn btn-outline-primary">
                        Work certificate Request
                    </a>
                  </div>

                  <div class="card-body">

                        <div class="form-group">
                            <label class="text-info" for="fullname">Full Name: @error('fullname')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="fullname" placeholder="Full Name" class="form-control @error('fullname') is-invalid @enderror" disabled value="{{$employee->fullname }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="registration_number">Registration Number: @error('registration_number')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="registration_number" placeholder="Registration Number" disabled class="form-control @error('registration_number') is-invalid @enderror" value="{{ $employee->registration_number }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="depart">Departement: @error('depart')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="depart" placeholder="Departement" disabled class="form-control @error('depart') is-invalid @enderror" value="{{ $employee->depart }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="hire_date">Hire date: @error('hire_date')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="date" name="hire_date" placeholder="Hire date" disabled class="form-control @error('hire_date') is-invalid @enderror" value="{{ $employee->hire_date }}">
                        </div>
                          <div class="form-group">
                            <label class="text-info" for="phone">Phone: @error('phone')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="tel" name="phone" placeholder="Phone" disabled class="form-control @error('phone') is-invalid @enderror" value="{{ $employee->phone}}">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="address">Address: @error('address')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="address" placeholder="Address" disabled class="form-control @error('address') is-invalid @enderror" value="{{ $employee->address }}">
                        </div>
                        <div class="form-group">
                            <label class="text-info" for="city">City: @error('city')<span class="text-danger">{{ $message }} </span>@enderror</label>
                            <input type="text" name="city" placeholder="City" disabled class="form-control @error('city') is-invalid @enderror" value="{{$employee->city}}">
                        </div>
                  </div>
              </div>

          </div>
        </div>
</div>
@endsection

@section('js')

@endsection

resources/views/employees/vacation.blade.php
@extends('adminlte::page')
@section('plugins.Datatables',true)
@section('title')
Employee Vacation | laravel employee App
@endsection

@section('content_header')
<h1><i class="fa fa-user"></i> Employee Vacation Request </h1>
@endsection

@section('content')

     <div class="container">
     <div class="row my-5">
         <div class="col-lg-8 col-10 mx-auto">
            <div class="card p-5 my-5">
                <div class="card-header">
                    <h2><img    width="50" height="50" src="https://cdn.pixabay.com/photo/2016/08/25/07/30/red-1618916_960_720.png" alt=""> Tech Web</h2>
                    <div class="text-right">
                        <h2>Vacation request </h2>
                        <h4 class="text-end">{{ Carbon\Carbon::now() }}</h4>
                    </div>

                </div>
                <div class="card-body">
                    <p class="lead">
                        <b>{{ $employee->fullname }}</b> is presently employed with me in the following :
                    </p>
                    <p class="lead">
                        <b>{{ $employee->depart }}</b> department.
                    </p>
                    <p class="lead">
                        he is requesting a vacation starting from <b>_________</b>
                    </p>
                    <p class="lead">
                        and ends on <b>_________</b>
                    </p>
                    <p class="m-5">
                       signature ________
                    </p>
                    <div id="print" class="">
                        <a href=""  onclick="
                        document.getElementById('print').style.display ='none';
                        setTimeout(function(){
                            document.getElementById('print').style.display ='block';
                        },2000);

                        window.print();"
                        class="btn btn-sm btn-primary"><i  class="fa fa-print"></i></a>
                    </div>
                </div>
            </div>
        </div>
</div>

@endsection

@section('js')
<script>
    $(document).ready(function(){
        $('#myTable').DataTable({
            dom : 'Bfrtip',
            buttons : [
                'copy',
                'excel',
                'pdf',
                'csv',
                'print',
                'colvis',
                'pageLength',
            ]
        });
    });
    function deleteEmp(id){
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {

                if (result.isConfirmed) {
                    document.getElementById(id).submit();
                    Swal.fire(
                    'Deleted!',
                    'Employee has been deleted.',
                    'success'
                )
            }
        })
    }

</script>
@if (session()->has('success'))
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '{{session()->get("success")}}',
            showConfirmButton: false,
            timer: 1500
        })
    </script>
@endif

@endsection

resources/views/home.blade.php
@extends('adminlte::page')

@section('title')
Home | laravel employee App
@endsection

@section('content_header')
<h1>Dashboard</h1>
@endsection

@section('content')

     <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{ App\Models\Employee::count() }}</h3>

                <p>Employees</p>
              </div>
              <div class="icon">
                <i class="fa fa-users"></i>
              </div>
              <a href="{{ url('admin/employee') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>

@endsection

resources/views/layouts/alert.blade.php
<div class=" mx-auto">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    @yield('styles')
    <title>@yield('title')</title>
  </head>
  <body class="bg-light">
        @yield('content')
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    @yield('scripts')
  </body>
</html>